# Generated by Django 5.2.6 on 2025-09-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prompts', verbose_name='картинка')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prompt', verbose_name='промпт')),
            ],
            options={
                'verbose_name': 'Картинка из промпта',
                'verbose_name_plural': 'Картинки из промптов',
            },
        ),
    ]
