# Generated by Django 5.2.6 on 2025-10-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promptlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptlike',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
